Repository laminas/laminas-di, pull requests merged in 2020-09, with the labels that each got.

#11 Custom logger
  docs/book/codegen.md
  src/Container/GeneratorFactory.php
  test/Container/GeneratorFactoryTest.php
Labels: Enhancement

#12 Fix handling of aot namespace config
  src/GeneratedInjectorDelegator.php
Labels: Bug

#13 Adds new page for installation to documentation
  docs/book/installation.md
  docs/book/quick-start.md
  mkdocs.yml
Labels: Documentation, Enhancement
