Repository laminas/laminas-di, pull requests merged in 2022-02, with the labels that each got.

#34 Update documentation to fix typos and inconsistencies in code samples, fixed grammar issues
  docs/book/v3/config.md
  docs/book/v3/cookbook/aot-guide.md
  docs/book/v3/cookbook/use-with-psr-containers.md
  docs/book/v3/cookbook/use-with-servicemanager.md
  docs/book/v3/injector.md
  docs/book/v3/migration.md
Labels: Bug, Documentation

#35 CONFIG: Remove redundant shorthand ternary & fix typos
  src/Config.php
Labels: Enhancement

#37 Drop PHP 7.3 support, prepare for Renovate with reusable workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  composer.json
  composer.lock
  phpunit.xml.dist
Labels: Enhancement

#38 INJECTOR: Add test for `Injector::create()` given existing Interface and update `Injector::createInstance`
  src/Injector.php
  test/InjectorTest.php
Labels: Bug

#39 ABSTRACT INJECTOR: Extract method into AbstractInjector::hasFactory
  src/CodeGenerator/AbstractInjector.php
Labels: Enhancement

#40 Generator trait produces incorrect exception message for invalid directory paths
  src/CodeGenerator/GeneratorTrait.php
  test/CodeGenerator/GeneratorTraitTest.php
Labels: Bug, Enhancement

#41 RUNTIME DEFINITION: Extract method into `RuntimeDefinition::ensureClassExists`
  src/Definition/RuntimeDefinition.php
Labels: Enhancement

#42 Apply PHP 7.4 Syntax
  src/CodeGenerator/AbstractInjector.php
  src/CodeGenerator/AutoloadGenerator.php
  src/CodeGenerator/FactoryGenerator.php
  src/CodeGenerator/InjectorGenerator.php
  src/Container/ServiceManager/AutowireFactory.php
  src/Definition/Reflection/ClassDefinition.php
  src/Definition/RuntimeDefinition.php
  src/LegacyConfig.php
  src/Resolver/AbstractInjection.php
  src/Resolver/DependencyResolver.php
  src/Resolver/TypeInjection.php
  test/CodeGenerator/AbstractInjectorTest.php
  test/ConfigTest.php
  test/Container/AutowireFactoryTest.php
  test/Container/ConfigFactoryTest.php
  test/Container/GeneratorFactoryTest.php
  test/DefaultContainerTest.php
  test/GeneratedInjectorDelegatorTest.php
  test/InjectorTest.php
  test/LegacyConfigTest.php
  test/Resolver/AbstractInjectionTest.php
  test/Resolver/DependencyResolverTest.php
  test/Resolver/ValueInjectionTest.php
  test/TestAsset/Constructor/ManyArguments.php
  test/TestAsset/GeneratedInjector.php
Labels: Enhancement
